backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img

collections:
  - name: pages 
    label: Homepage
    folder: public/pages
    extension: md
    fields: 
      - { label: Share Image, name: meta_image, widget: image }
      - { label: Share Description, name: meta_desc, widget: string }
      - { label: Address, name: address, widget: string }
      - { label: Instagram URL, name: ig_url, widget: string }
      - { label: Reservations Label, name: rsv_label, widget: string }
      - { label: Reservations URL, name: rsv_url, widget: string }