backend:
  name: git-gateway
  # branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: fr

collections:
  - name: pages 
    label: Pages
    i18n:
      structure: single_file
      locales: [en, fr]
    files:
      - name: Home
        label: Homepage
        file: content/home.md
        i18n: true
        fields: 
          - { label: Address, name: address, widget: string, i18n: true }
          - { label: Instagram URL, name: ig_url, widget: string }
          - { label: Reservations Label, name: rsv_label, widget: string, i18n: true }
          - { label: Reservations URL, name: rsv_url, widget: string }